---
kind: pipeline
type: docker
name: lint

steps:
  - name: lint
    image: mwalbeck/python-poetry:1-3.10
    pull: if-not-exists
    environment:
      APP_DIR: autoklik
      POETRY_VIRTUALENVS_CREATE: "false"
    commands:
      - poetry install
      - black --check $${APP_DIR}
      - flake8 $${APP_DIR}

trigger:
  event:
    - pull_request
    - tag

---
kind: pipeline
type: docker
name: release

steps:
  - name: release
    image: mwalbeck/python-poetry:1-3.10
    pull: if-not-exists
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
      POETRY_PYPI_TOKEN_PYPI:
        from_secret: poetry_pypi_token
    commands:
      - poetry install
      - poetry publish --build

trigger:
  event:
    - tag

depends_on:
  - lint

---
kind: signature
hmac: f9396c1a60d3a760cbd0e4d5667a0386c1a0356894362b8c3efe82b05f979a3c

...
