---
kind: pipeline
type: docker
name: lint

steps:
  - name: lint
    image: mwalbeck/python-poetry:1.2-3.10
    pull: if-not-exists
    environment:
      APP_DIR: autoklik
      POETRY_VIRTUALENVS_CREATE: "false"
    commands:
      - poetry install
      - black --check $${APP_DIR}
      - flake8 $${APP_DIR}

trigger:
  event:
    - pull_request
    - tag

---
kind: pipeline
type: docker
name: release

steps:
  - name: release
    image: mwalbeck/python-poetry:1.2-3.10
    pull: if-not-exists
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
      POETRY_PYPI_TOKEN_PYPI:
        from_secret: poetry_pypi_token
    commands:
      - poetry install
      - poetry publish --build

trigger:
  event:
    - tag

depends_on:
  - lint

---
kind: signature
hmac: 19dea5db733c4d2ba570e8c25d3e89ac6df6067f16af2b1beeb83ff339704216

...
