---
kind: pipeline
type: docker
name: lint

steps:
  - name: lint
    image: mwalbeck/python-poetry:1.1-3.8
    pull: if-not-exists
    environment:
      APP_DIR: autoklik
      POETRY_VIRTUALENVS_CREATE: "false"
    commands:
      - poetry install
      - black --check $${APP_DIR}
      - flake8 $${APP_DIR}

trigger:
  event:
    - pull_request
    - tag

---
kind: pipeline
type: docker
name: release

steps:
  - name: release
    image: mwalbeck/python-poetry:1.1-3.8
    pull: if-not-exists
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
      POETRY_PYPI_TOKEN_PYPI:
        from_secret: poetry_pypi_token
    commands:
      - poetry install
      - poetry publish --build

trigger:
  event:
    - tag

depends_on:
  - lint

---
kind: signature
hmac: d8f985d32d56000b445e61e495ba456eb137c4832846534c811b684ce96d55f4

...
